= C#/.NET Style Guide


== Layout Conventions

Good layout uses formatting to emphasize the structure of your code and to make the code easier to read.


* Write only one statement per line.

* Write only one declaration per line.

* Add at least one blank line between method definitions and property definitions.

* Use parentheses to make clauses in an expression apparent, as shown in the following code.

* Do not write lines longer than 100 characters.

Do's:
....
if ((val1 > val2) && (val1 > val3))
{
    //Take appropriate action.
}
....

Don'ts
....
if((val1 > val2)&&(val1 > val3)){
    //Take appropriate action.
}
....


== Language Guidelines

The following sections describe practices that the C# team follows to prepare code examples and samples.

* If you append/concat multiple strings together, use a 'StringBuilder' to improve performance.

* Do NOT use the keyword 'var' to create an implicit typed variable if you use a common type.

* Only catch exceptions if you can handle them or if you need to close connections and streams
** Do not use empty 'catch' blocks or 'catch (System.Exception)' to catch all 
exceptions.

* Prefer english language for code and comments.

* Prefer Properties instead of functions to get/set a variable.


== Naming Conventions

=== PascalCase and camelCase

* Use meaningful method/function and variable names.
** Examples:
*** maxConcurrentConnection instead of maxConn
*** unbalancedAccountList instead of accountingList
*** documentToBeDeleted instead of document
*** remindersOfStep2 instead of Rmd2
** Include verbs into the names
** Use prefixes such as Get[...], Set[...].
** Start local variables with camelCase (starting with lowercase and the first letter of each word (except for the first one is uppercase)).
*** Examples:
**** Do: deleteAdressFromChache 
**** Do NOT: delete_adress_from_chache or delete-adress-from-chache
** Start namespaces, classes and methods/functions with PascalCase (the letter of each word starts uppercase).
*** Examples:
**** Do: ZeissManagementSystem, ExcelHandler, ReadExcel, WriteExcel 
**** Do NOT: Zeiss_Management-System, excelHandler, read_excel, write-excel

=== Interfaces

* Use 'I' (uppercase of 'i') in front of interfaces to mark them as interface.
** Interfaces use PascalCase.
*** Examples:
**** IComparer, IComperable, IEnumerable

=== Case Convention Table

When to use PascalCase and camelCase?:

|=======
|Identifier |Convention |Example
|Namespace |PascalCase |System.Workflow.ComponentModel
|Type | PascalCase |public sealed class DataContractSerializer
|Property |PascalCase |public string ProcessID {get; set;}
|Method/Function |PascalCase |public void Dispose()
|Field |PascalCase |private static Padding FormPadding
|Field |PascalCase |private string UserWindowText
|Delegate/Event |PascalCase |public delegate void PropertyChangedEventHandler
|Enum(eration) |PascalCase |Internal enum Severity
|Interface |I+PascalCase |public interface ICompareable
|Parameter |camelCase |public bool Contains(T value)
|Local Variable |camelCase |int counter
|=======

=== Namespaces

We are using the following naming convention to name namespaces:
Companyname.Product.Layer.Modul.Submodul
(Note: Submoduls also can contain submodules).
Also it should be clear in the namespace name what the namespace id doing.

In our case is the Companyname "Zeiss" and the Productname "PublicationManager".
We have 3 Layer: UI (for UI), Businesss (for Bussines Logic) and Data (for IO Opeartions).

Because multiple persons can work on one module/submodule, we're using the single responsible convention.
One namespace should only do one thing (such as searching, filtering, reading, writing, displaying, [...]).

Here are some examples:
Zeiss.PublicationManager.UI.Pages.AddPublication   (Contains all Razor Pages for the UI that are used to add a publication)
Zeiss.PublicationManager.UI.Pages.SearchPublication   (Contains all Razor Pages for the UI that are used to search a publication)
Zeiss.PublicationManager.UI.Pages.UpdatePublication   (Contains all Razor Pages for the UI that are used to update a publication)

with that way multiple persons can work on various pages withot beeing distracted from classes and code for other pages.

More examples:
Zeiss.PublicationManager.Business.Logic.IO.Write (Contains all code that is used to write/change publications)
Zeiss.PublicationManager.Business.Logic.IO.Read (Contains all code that is used to read publications)
Zeiss.PublicationManager.Business.Logic.FilterPublication (Contains all code that is used to filter publications)
Zeiss.PublicationManager.Business.Logic.SearchPublication (Contains all code that is used to search publications)

in that example it is possible to create the code for searching/filtering, even if IO does not work properly.

Some other examples:
Zeiss.PublicationManager.Data.DataSet.IO.Write (Contains all code that is used to write/change publications)
Zeiss.PublicationManager.Data.DataSet.IO.Read (Contains all code that is used to read publications)
Zeiss.PublicationManager.Data.Excel.IO.Write (Contains all code that is used to write/change Excel entries)
Zeiss.PublicationManager.Data.Excel.IO.Read (Contains all code that is used to read Excel entries)

as you saw in all examples above many namespaces look very similar and namespaces with similar names do almost the same thing. That makes the namespaces easier to use and it is easier to find the wished namespaces and classes.
