= System-Wide Requirements: ZEISS Verwaltungssystem
Nina Püschmann s79289@htw-dresden.de; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt "ZEISS-Verwaltungssystem für Veröffentlichungen" spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten.

== Systemweite funktionale Anforderungen (F)
* F1: Mit Ausnahme der Einsicht und Filterung nach bestimmten Einträgen muss das System eine Authorisierung fordern.
* F2: Der Export der Daten erfolgt in eine Excel-Datei (ist durch die Verwendung von Excel als Daten Bank gegeben).

== Qualitätsanforderungen für das Gesamtsystem

=== Benutzbarkeit (Usability)
* U1: Ein durchschnittlicher Internetnutzer muss ohne Anleitung in der Lage sein, alle Funktionen des Systems zu bedienen.
* U2: Keine Aktion wird mehr als 5 Mausklicks erforderlich machen.
* U3: Mehr als 80% der User sollen zufrieden mit der Anwendung sein.
* U4: Jede System- oder Fehlermeldung muss eindeutig für den User sein.

=== Zuverlässigkeit (Reliability)
* R1: Das System soll 99,5% Verfügbarkeit pro Jahr (43,8h Downtime pro Jahr) mit maximal 4h Ausfallzeit am Stück haben.
* R2: Nach Störungen muss das System alle eingegebenen Daten wiederherstellen. 

=== Leistung (Performance)
* P1: Das System muss bis zu 20 Nutzer gleichzeitig unterstützen können.
* P2: Der Wechsel zwischen zwei verschiedenen Ansichten darf für den Nutzer nicht länger als 2 Sekunden dauern.
* P3: Start- und Shutdownzeit darf nicht länger als 8 Sekunden dauern.

=== Unterstützbarkeit (Supportability)
* S1: Das System soll einfach um Änderungsmitteilungen erweiterbar sein.
* S2: Das System soll einfach um eine Statistikerzeugung zu den Einträgen erweiterbar sein.
* S3: Die Anwendung wird nicht mit firmeninterner IT korrelieren.
* S4: Das System soll auf Windows 10 laufen.

== Zusätzliche Anforderungen
=== Einschränkungen (Constraints)
* C1: Das System muss Windows-kompatibel sein.
* C2: Das System wird eine online-Datenbank nutzen.
* C3: Das Backend wird mit C# programmiert.
* C4: Das Frontend wird mit HTML/CSS programmiert.
* C5: Die Anwendung wird über das Webframework Blazor laufen.

=== Organisatorische Randbedingungen (Interface Requirements)
* I1: Die Anwendung muss für verschiedene Bildschirmgrößen nutzbar sein.
* I2: Filter sollen über ein ausklappbares Akkordeon auswählbar sein.
* I3: Ein Workflow soll den Nutzer durch eine Hinzufügung navigieren.

=== Rechtliche Anforderungen (Business Rules)
* B1: Bei gewünschter Hinzufügung muss das Sales Department kontaktiert werden, welches die Rechte für Hinzufügungen innehat.
* B2: Die Anwendung darf nur firmenintern genutzt werden und Daten dürfen nciht weitergegeben werden.
