== Use-Case: Veröffentlichung hinzufügen

Ein Autor der ZEISS hat einen Fachbeitrag erstellt/geschrieben, welcher bereits vollständig von einem Herausgeber veröffentlicht wurde. Nun soll diese Veröffentlichung namentlich gelistet werden (inkl. optionaler Angaben), damit sich z.B. andere Mitarbeiter über getätigte Veröffentlichungen informieren können.

===	Kurzbeschreibung der Akteure
==== Nutzer
Ein Nutzer hat das Recht, eine Veröffentlichung hinzuzufügen. Jeder Mitarbeiter von ZEISS ist Nutzer und kann einen Antrag einer Listung von einem Fachbeitrag stellen, welcher danach vom Sales Department geprüft und bei Korrektheit veröffentlicht wird. Der Nutzer muss sich nicht einloggen.

==== Sales Department (SD)
Das Sales Department verfügt über die Rechte, beantragte Einträge zu veröffentlichen sowie auch selbst Beiträge hinzufügen, wenn es dafür über andere Kommunikationskanäle die erforderlichen Infromationen erhalten hat.

==== Autor
Ein Autor ist diejenige Person, welche der/die Urheber/in eines Fachbeitrags ist. Der Fachbeitrag wurde bereits in einem Medium veröffentlicht und soll nun intern gelistet werden. 

==== Herausgeber
Entspricht einer öffentlichen Plattform / einem Medium, auf / von welcher der vom Autor erstellten Fachbeitrag inhaltlich und in Gänze veröffentlicht wurde.

=== Vorbedingungen
* Die Anwendung ist installiert und geöffnet
* Das SD ist als solches eingeloggt 

=== Standardablauf (Basic Flow)

. Der Use Case beginnt, wenn ein Nutzer "Veröffentlichung hinzufügen" auswählt
. Es beginnt ein Workflow, Nutzer wird aufgefordert, schrittweise Pflichtangaben zu machen. 
* Wenn die jeweils geforderten Eingaben nicht gemacht werden, bekommt der Nutzer eine Fehlermeldung und wird aufgefordert, die letzte Eingabe vollständig zu machen. 
* Plichtangaben sind folgende:
** Dokumenttitel (entspricht dem Titel, unter welchem die Veröffentlichung vom Herausgeber veröffentlicht wurde)
** Vorname, Nachname des Autors
** Datum der Veröffentlichung
** Geschäftsbereich des Autors 
** Art der Veröffentlichung
. Der Nutzer navgiert mit den Buttons "Weiter" und "Zurück" durch die Angaben.
. Wenn der Nutzer alle Pflichteingaben gemacht hat, erscheint die Buttons "Veröffentlichung hinzufügen" und "Optionale Angaben".
. Nutzer kann an der Stelle optionale Angaben hinzufügen. Diese können folgende sein:
* Name des Herausgebers
* Beschreibung (Infobox)
* Tags auswählen
.. Diese Angaben sind optional, der Nutzer wird auch durch diese über einen Workflow geleitet.
.. Bei Unvollständigkeit kann der Nutzer trotzdem über "Weiter" und "Zurück" durch die Eingaben navigieren, ohne dass er zur Eingabe aufgefordert wird.
. Nutzer navigiert bis zum Ende über "Weiter" und dann erscheint der Button "Veröffentlichung beantragen".
. Antrag wird direkt ans Sales Department gesendet, welches den Antrag prüft und bei Vollständigkeit und Korrektheit der Daten veröffentlicht.
. Der Use Case ist abgeschlossen.

=== Wesentliche Szenarios
==== Erfolgreiche Hinzufügung eines Fachbeitrags
Ein Fachbeitrag wurde erfolgreich gelistet und ist nun für alle Nutzer mit allen Informationen sichtbar.

==== Abbruch einer Hinzufügung 
Es kommt durch den Nutzer zum Abbruch des Hinzufügungs-Flows und die Eingaben werden nicht gespeichert.

==== Falsche Angaben wurden gemacht
Durch den Nutzer wurden falsche Angaben gemacht, welche dem Sales Department auffallen. Danach bestehen folgende Möglichkeiten:
. Das SD bearbeitet den Fehler, da dem Sales Department die korrekten Angaben vorliegen und veröffentlicht anschließend den Beitrag.
. Das SD fordert den Nutzer auf, die falschen Angaben zu korrigieren wartet einen neuen Antrag ab.

//==== Abbruch einer Hinzufügung mit Speicherung des Entwurfes
//Es kommt durch den Nutzer zum Abbruch des Hinzufügungs-Flows, er hat aber die Möglichkeit, seine bereits eingegebenen Daten als Entwurf zu speichern.

=== Alternative Abläufe
==== (5.) Bereich hinzufügen
Wenn Geschäftsbereich noch nicht existiert, kann dieser hinzugefügt werden.

. Neben der Bereichsauswahl gibt es die Möglichkeit, weitere Bereiche hinzuzufügen.
. Bereich wird dann ins System aufgenommen.
. Aktueller Beitrag kann dem neu hinzugefügten Bereich zugeordnet werden.
. Use Case wird bei fortgesetzt bei der Angabe der Optionalen Angaben.

==== (5.) Tag hinzufügen
Wenn ein Tag zu Beschreibungszwecken hinzugefügt werden soll, welcher noch nicht im System existiert, kann dieser hinzugefügt werden.

. Neben der Tagauswahl gibt es die Möglichkeit, weitere Tags hinzuzufügen.
. Tag kann danach unter den optionalen Angaben ausgewählt und dem Beitrag hinzugefügt werden.
. Use Case wird bei fortgesetzt bei der Angabe der Optionalen Angaben.

===	Nachbedingungen

==== Beitrag in Liste aufgenommen
Der Fachbeitrag ist nun gelistet.
