== Use-Case 03: Veröffentlichung bearbeiten

=== Kurzbeschreibung
In diesem Use-Case wird das Bearbeiten einer Veröffentlichung durch das Sales Department beschrieben.

===	Kurzbeschreibung der Akteure

*Sales Department*

Das Sales Department will eine Veröffentlichung bearbeiten.

=== Vorbedingungen
* Die Software ist installiert und geöffnet
* Liste der Veröffentlichungen ist nicht leer
* Sales Department ist als solches autorisiert

=== Standardablauf (Basic Flow)

. Der Use-Case beginnt, wenn das Sales Department "Fachbeitrag suchen" auswählt.
. Das System gibt eine Übersicht von Veröffentlichungen aus.
. Das Sales Department wählt bei gewünschter Veröffentlichung "Bearbeiten" aus.
. Das System gibt einen Workflow zur Bearbeitung von Pflichtangaben und Optionaldaten aus.
. Das Sales Department ändert den Wert der zu bearbeitenden Angabe.
. Das Sales Department wählt "Speichern" aus.
. Das System speichert sämtliche eingetragenen Angaben.
. Der Use-Case ist abgeschlossen.

=== Wesentliche Szenarios

*Beitrag bearbeiten*

* Sc1: Sales Department Mitarbeiterin A wählt Veröffentlichung X aus Übersicht aus. A ändert unter Art der Veröffentlichung den Wert von "Artikel" zu "Vortrag". A speichert die vorgenommene Änderung ab.

===	Nachbedingungen

==== Bearbeitete Veröffentlichung 
Attribute eines Fachbeitrags liegen nun verändert im System vor und können nun unter diesen gefunden werden.


