== Use-Case 01: Veröffentlichung hinzufügen

=== Kurzbeschreibung
In diesem Use-Case wird das Hinzufügen einer Veröffentlichung durch einen Autor (oder das Sales Department) beschrieben.

===	Kurzbeschreibung der Akteure

*Autor*

Der Autor will eine Veröffentlichung in die Liste eintragen. 


*Sales Department*

Das Sales Department überprüft die eingetragenen Veröffentlichungen und kann eine Veröffentlichung im Auftrag eines Autors in die Liste eintragen.

=== Vorbedingungen
* Fachbeitrag wurde von Herausgeber bereits veröffentlicht
* Die Software ist installiert und geöffnet
* Das Sales Department ist als solches eingeloggt 

=== Standardablauf (Basic Flow)

. Der Use-Case beginnt, sobald "Veröffentlichung hinzufügen" auswählt wird.
. Der Autor (oder das Sales Department) gibt in einem Workflow schrittweise sämtliche Pflichtangaben ein.
. IF jeweilige Pflichtangabe eingetragen UND "Weiter" auswählt
.. Der Autor (oder das Sales Department) navigiert mit "Weiter" zur jeweiligen nächsten Pflichteingabe.
. ELSE jeweilige Pflichtangabe nicht eingetragen UND "Weiter" auswählt
.. Ausgabe Dialogfenster mit entsprechender Fehlermeldung und Aufforderung zur erneuten Eingabe. 
.. Der Autor (oder das Sales Department) bestätigt mit "Okay".
.. Das Dialogfenster schließt sich.
. Der Autor (oder das Sales Department) navigiert mit "Zurück" zur jeweiligen vorherigen Pflichtangabe.
. Am Ende des Workflows erscheinen die Buttons "Veröffentlichung hinzufügen" und "Optionale Angaben".
. IF Auswahl "Veröffentlichung hinzufügen"
.. Alle bisher eingetragenen Angaben werden abgeschickt.
. ELSE Auswahl "Optionale Angaben"
.. Es öffnet sich ein weiterer Workflow zur Eingabe optionaler Daten, welcher nicht vollständig sein muss.
.. Der Autor (oder das Sales Department) navigiert mit "Weiter" oder "Zurück" jeweils zur nächsten Eingabe oder zur vorherigen Eingabe im Workflow.
. Das System gibt eine Vorschau der Veröffentlichung als Übersicht aller eingegebenen Daten aus.
. IF "Vorschau beenden" auswählt
.. Der Autor (oder das Sales Department) gelangt in den ursprünglichen Workflow
. ELSE "Veröffentlichen" auswählt
.. Dialogfenster mit erfolgreichem Hinzufügen wird ausgegeben.
.. Der Autor (oder das Sales Department) gelangt über "Weiter" zur Landing Page.
. Antrag wird direkt an das Sales Department gesendet.
. Der Use-Case ist abgeschlossen.

=== Alternative Abläufe

*(3.) neuen Geschäftsbereich eines Autors hinzufügen*

. Der Autor (oder das Sales Department) wählt im Abschnitt "Geschäftsbereich des Autors" des Workflows "Neuer Geschäftsbereich" aus
. Ein Dialogfenster mit Textfeld öffnet sich
. Der Autor (oder das Sales Department) trägt in das Textfeld den gewünschten Geschäftsbereich ein
. Mit der Auswahl von "Hinzufügen" wird der Geschäftsbereich anschließend hinzugefügt

////
==== (.) neuen Tag hinzufügen
Wenn ein Tag zu Beschreibungszwecken hinzugefügt werden soll, welcher noch nicht im System existiert, kann dieser hinzugefügt werden.

. Neben der Tagauswahl gibt es die Möglichkeit, weitere Tags hinzuzufügen.
. Tag kann danach unter den optionalen Angaben ausgewählt und dem Beitrag hinzugefügt werden.
. Use Case wird bei fortgesetzt bei der Angabe der Optionalen Angaben.
////

=== Wesentliche Szenarios

*Erfolgreiches Hinzufügen einer Veröffentlichung*

* Sc1: Der Autor A wählt im System "Veröffentlichung hinzufügen" aus. Er gibt im Workflow Titel,  ein und navigiert mit "Weiter" zur nächsten Pflichteingabe. Nachdem er sämtlich Eingaben getätigt hat, wählt er am Ende des Workflows "Veröffentlichung hinzufügen" aus. Eine Veröffentlichung wurde erfolgreich hinzugefügt und ist nun für alle Autoren (oder das Sales Department) mit allen Informationen sichtbar.

*Abbruch beim Hinzufügen*

* Sc2: Der Autor B befindet sich im Workflow zu Eingabe der Pflichtdaten. Autor B schließt die Anwendung. Das System bricht die Eingabe ab und verwirft alle Eingaben.

*Falsche Angaben wurden gemacht*

* Sc3: Der Autor C wählt im System "Veröffentlichung hinzufügen" aus. Autor C gibt als Titel "XYZ" ein, anstelle von "ABC". Nach der Eingabe der restlichen Angaben speichert er die Veröffentlichung. Das Sales Department Mitarbeiterin X bemerkt bei Prüfung der Angaben den Fehler. Folgende Möglichkeiten bestehen anschließend:

** Sales Department Mitarbeiterin X bearbeitet den Fehler, da Sales Department Mitarbeiterin X die korrekten Angaben vorliegen und fügt die Veröffentlichung der Liste hinzu.
** Sales Department Mitarbeiterin X fordert Autor C auf, die falschen Angaben zu korrigieren.

////
==== Abbruch beim Hinzufügen mit Speicherung des Entwurfes
Der Workflow wird durch den Autor (oder das Sales Department) abgebrochen, es besteht aber die Möglichkeit, seine bereits eingegebenen Daten als Entwurf zu speichern.
////

===	Nachbedingungen

==== Beitrag in Liste aufgenommen
Der Fachbeitrag ist nun gelistet.
