== Use-Case: Veröffentlichung hinzufügen

Wenn ein 

===	Kurzbeschreibung der Akteure
==== Mitarbeiter Sales Department (SD)
Nur die (3) Verantwortlichen im Sales Department haben das Recht, den Namen und die Beschreibungn einer Veröffentlichung in die Liste aufzunehmen. Dazu bekommen die Verantwortlichen (und auch nur die) einen Zugang und müssen sich einloggen.

==== Autor
Der Autor ist der Autor der Veröffentlichung und tritt mit dem SD in Kontakt, damit seine Veröffentlichung in die Liste aufgenommen wird. Er muss sich nicht einloggen, er gibt lediglich die nötigen Informationen bezüglich seiner Veröffentlichung ans SD.

=== Vorbedingungen
* Eine Person des SD ist im System angemeldet.
* Es fand eine Veröffentlichung eines Mitarbeiters statt, welche noch nicht im System gelistet ist.
* Zur neuen Veröffentlichung liegen dem Sales Department alle Informationen vor, die mit eingegeben werden sollen
** *mindestens Vorname, Nachname des Autors, dessen Geschäftsbereich, Datum und Art der Veröffentlichung*

=== Standardablauf (Basic Flow)


. Der Use Case beginnt, wenn eine berechtigte Person eine Veröffentlichung hinzufügen möchte
. Es öffnet sich eine Ansicht, in der alle oben genannten Eintragungen gemacht werden müssen
* *SPÄTER:* zusätzlich können noch weitere Angaben gemacht werden (Tags, zusätzliche Informationen)
. Nutzer wählt "Veröffentlichung hinzufügen"
. Die Veröffentlichung wird der Liste zugefügt
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
==== Nicht alle notwendigen Felder ausgefüllt
Wenn nicht alle notwendigen Angaben zu einer neuen Veröffentlichung durch das Sales Department gemacht werden

. erfolgt eine Fehlermeldung, dass obligatorische Angaben fehlen 
. Nutzer wird zur Bearbeitung weitergeleitet und kann fehlende Angaben hinzufügen und bestehende verändern
. Wird dann weitergeleitet zu "Veröffentlichung hinzufügen"

==== Nutzer möchte zusätzliche Angaben zum Fachbeitrag machen
Wenn die obligatorischen Felder für eine Beschreibung des Fachbeitrages unzureichend sind

. kann das Sales Department unter "Weitere Angaben" verschiedene Informationen hinzufügen
* Tags
* Beschreibungen (Infobox)
* Verlag des Mediums
. Use Case wird bei "Veröffentlichung hinzufügen" fortgesetzt

==== Bereich hinzufügen
Wenn ein Autor aus einem Geschäftsbereich veröffentlicht, welcher noch nicht hinzugefügt ist

. Neben dem Drop-Down gibt es die Möglichkeit, weitere Bereiche hinzuzufügen
. Bereich wird dann ins System aufgenommen
. Aktueller Beitrag kann dem neu hinzugefügten Bereich zugeordnet werden
. Use Case wird bei "Veröffentlichung hinzufügen" fortgesetzt

=== Wesentliche Szenarios
==== Veröffentlichung hinzufügen

. Sales Department Mitarbeiter wählt "Veröffentlichung hinzufügen"
. Es öffnet sich eine Ansicht, in der alle oben genannten Eintragungen gemacht werden *müssen*
* *SPÄTER:* zusätzlich können noch weitere Angaben gemacht werden (Tags, zusätzliche Informationen)
. Sales Department Mitarbeiter wählt "Veröffentlichung hinzufügen"
. Die Veröffentlichung wird der Liste zugefügt
. Der Use Case ist abgeschlossen.

===	Nachbedingungen

==== Beitrag in Liste aufgenommen
Der Fachbeitrag ist nun gelistet.

==== Tags/zusätzliche Information hinuzgefügt
Die Beschreibung des Fachbeitrages wurde verändert.

==== Bereich hinzugefügt
Ein neuer Bereich wurde hinzugefügt und kann nun standardmäßig bei Bearbeitung/Neuhinzufügung als Bereich ausgewählt werden.
