== Use-Case 02: Veröffentlichung suchen

=== Kurzbeschreibung
Das Uses-Case wird als Suchvorgang einer Veröffentlichung von dem Benutzer beschrieben. 

===	Kurzbeschreibung der Akteure

*Autor*

Der Autor will nach einer Veröffentlichung suchen.


=== Vorbedingungen
* (Der Benutzer befindet sich im Netzwerk - konkret auf Zeiss beziehen?)
* Liste der Veröffentlichungen ist nicht leer - eine Exceldatei wurde auf der StartPage ausgewählt (bzw. importiert)
* portables Systems muss geöffnet werden können


=== Standardablauf (Basic Flow)

. Der Use-Case beginnt, wenn der Benutzer einen Begriff in das Suchfeld eingibt(auf Main Page).  
. System nimmt die Eingabe entgegen
. System vergleicht Eingabe im Suchfeld mit gespeicherten Daten der ausgewählten Datei 
. Das System das Ergbnis aus (konkretieren?) 
. Der Use-Case ist abgeschlossen.

=== Alternative Abläufe

*(2.)Sortierung der Übersicht* ( Frage zugehörig zu Suchen?) 

. Der Benutzer wählt Sotierung
. System gibt Übersicht aus

////
==== Liste als CSV exportieren
Wenn der Nutzer seine Filterergebnisse als CSV exportieren will
. nach der Filterung gibt es die Möglichkeit, die angezeigte Liste mit ihren Informationen als CSV zu exportieren
. Kann einen Pfad zum Speichern auswählen, automatisch wird immer der Downloads-Ordner angesteuert
. Mit "Liste exportieren" wird diese als CSV gespeichert
////

=== Wesentliche Szenarios

*Veröffentlichung nach Schlagwort filtern*

* Sc1: Der Autor B möchte eine Liste mit allen Veröffentlichungen, welche als Art der Veröffentlichung "Workshop" aufweisen. Autor B gibt in das Suchfeld "Workshop" ein. Das System gibt alle Veröffentlichungen aus, die "Workshop" als Art der Veröffentlichung besitzen.


*Veröffentlichung nach Sortierung filtern*

* Sc2: Der Autor C will eine Übersicht der zuletzt veröffentlichten Fachbeiträge. Autor C wählt in der Übersichtsspalte des Datums der Veröffentlichung das Symbol zur Sortierung aus und stellt die Sortierung nach <absteigend sortieren> ein. Das System gibt Veröffentlichungen in absteigender Reihenfolge nach dem Datum aus.

===	Nachbedingungen
Der Autor oder das Sales Department hat eine Veröffentlichung gefunden.
