== Fachbeitrag veröffentlichen
===	Autor erstellt einen neuen Fachbeitrag


===	Kurzbeschreibung der Akteure
==== Autor
Der Autor ist für das Erstellen von Fachbeiträgen zuständig, welche dann mithilfe des Programmes veröffentlicht werden sollen.

=== Vorbedingungen
* Autor hat ein Konto 
* Autor ist angemeldet
* Autor hat die Berechtigung, Dokumente zu veröffentlichen 
* Autor hat eine Datei in einem zugelassenen Format in einem Verzeichnis, auf das er Zugriff hat 

=== Standardablauf (Basic Flow)

Ablauf beginnt, wenn "neuen Beitrag hinzufügen" gewählt wird

. Autor kann beliebige Anzahl (Aber max. <Anzahl>) Dateien auswählen, die er veröffentlichen will
. Diese kann er mit Beschreibungen versehen, Tags hinzufügen, die Art der Veröffentlichung auswählen etc.
. Wenn mit der Beschreibung zufrieden, kann die Veröffentlichung des Beitrags bestätigt werden
. Nach nochmaliger Kontrolle und Bestätigung des Veröffentlichenden wird der Fachbeitrag hinzugefügt

=== Alternative Abläufe

==== Vorzeitige Beendung der Veröffentlichung
Wenn Autor während des Veröffentlichungsprozesses auf Abbrechen klickt/Fenster schließt,

* fragen, ob er den Fortschritt speichern möchte
* fragen, ob er die aktuelle Veröffentlichung wirklich beenden möchte
** wenn nein, dann Rückkehr zur aktuellen Veröffentlichung

==== Verpflichtende Angaben zum Beitrag 
* Folgende Angaben zum Beitrag sind obligatorisch:
** Name des Autors
** Geschäftsbereich des Autors
** Datum der Veröffentlichung
** Art der Veröffentlichung
** Aktueller Status
* Wenn diese nicht vollständig angegeben, wird der Autor darauf hingewiesen
* Erst bei Vollständigkeit ist eine Veröffentlichung möglich


=== Wesentliche Szenarios

==== Fachbeitrag veröffentlichen
. Der Use Case beginnt, wenn der Autor eine Datei hochladen will.
. Autor klickt auf "*Veröffentlichung hinzufügen"*
. Autor *wählt Datei(en)* aus eigenem Verzeichnis aus, es ist eine maximale Anzahl von <Anzahl> Dateien möglich, auch nur die Formate <Formate>
. Autor fügt *eigenen Namen, seinen Geschäftsbereich und das Datum der Veröffentlichung* hinzu (muss automatisch geprüft werden, ob es sich um ein korrektes Datum handelt)
. Autor wählt über Dropdown-Menü *Art der Veröffentlichung* aus
* Artikel
* Blogbeitrag
* Workshop
* Vortrag
* Videotraining
* Buch
. Autor gibt Informationen zum *Medium* in Textfelder ein
* Name des Mediums
* Verlag
. Autor kann über ein Dropdown-Menü den *Status* seiner Veröffentlichung angeben
* Vorgeschlagen
* In Bearbeitung
* Eingereicht
* Abgelehnt
* Veröffentlicht
. Autor kann zusätzliche *Tags* hinzufügen
. Autor kann zusätzliche Informationen zum Beitrag in eine *Infobox* hineinschreiben
. Autor kann *Datenänderungen* durch den Reporter im Vorhinein widersprechen oder angeben, dass er immer gefragt werden muss, damit die datenänderung vollzogen werden kann; könnten in etwa so aussehen:
* ⧠ Datenänderungen zur Systematisierung widersprechen
* ⧠ Bei Datenänderungen immer gefragt werden

. Autor klickt auf *"Vorschau der Veröffentlichung ansehen"* und bekommt (bevor er veröffentlichen kann) eine Vorschau angezeigt, in der alle eingegebenen Daten angezeigt werden 
. Autor *prüft* eingegebenen Daten und kann über einen Button direkt wieder zur Bearbeitung springen
. Wenn die finale Bearbeitung abgeschlossen ist, kann der Autor auf *"Beitrag veröffentlichen"* klicken und der Beitrag wird veröffentlich
. Es erscheinen die Möglichkeiten, weitere Dateien zu veröffentlichen oder die letzte Veröffentlichung einzusehen 
. Der Use Case ist abgeschlossen.

==== Datenänderungen widersprechen

===	Nachbedingungen

==== Neuer Beitrag vorhanden
Mit der Bestätigung zur Veröffentlichung durch den Autor wird der Beitrag dem System hinzugefügt.

==== Eigenschaften filtern
Artikel wird den jeweils ausgewählten Eigenschaften aus den Drop-Down-Menüs hinzugefügt und ist bei einem Filtern nach angegebenen Eigenschaften dann unter diesen sichtbar. 

==== Neue Tags hinzugefügt
Beim Hinzufügen noch nicht vorhandener Tags durch den Autor werden diese zum System hinzugefügt und der Beitrag unter diesen auffindbar (bei Suche).


=== Besondere Anforderungen

==== Rechtliche Anforderung
Der hinzugefügte (oder bearbeitete) Beitrag muss vom Autor selbst verfasst und erstellt sein, Zitate oder Quellen müssen deutlich gekennzeichnet sein. Dies bestätigt der Autor mit der Veröffentlichung im System.
