== Use-Case 02: Veröffentlichung suchen

=== Kurzbeschreibung
In diesem Use-Case wird das Suchen nach einer Veröffentlichung durch einen Autor (oder das Sales Department) beschrieben.

===	Kurzbeschreibung der Akteure

*Autor*

Der Autor will nach einer Veröffentlichung suchen.


*Sales Department*

Das Sales Department will nach einer Veröffentlichung suchen.

=== Vorbedingungen
* Die Software ist installiert und geöffnet
* Liste der Veröffentlichungen ist nicht leer
* Sales Department ist als solches eingeloggt

=== Standardablauf (Basic Flow)

. Der Use-Case beginnt, wenn der Autor (oder das Sales Department) "Fachbeitrag suchen" auswählt.
. Das System gibt eine Gesamtübersicht von Veröffentlichungen aus.
. Der Autor (oder das Sales Department) gibt in Suchfeld ein Schlagwort ein.
. Das System vergleicht Pflichtdaten/Optionaldaten mit Schlagwort.
. Das System gibt gefilterte Übersicht mit entsprechenden Übereinstimmungen aus.
. Der Use-Case ist abgeschlossen.

=== Alternative Abläufe

*(2.)Sortierung der Übersicht*

. Der Autor (oder das Sales Department) stellt über Symbole in Übersicht Sortierung ein.
. Das System gibt Übersicht nach eingestellter Sortierung aus.

////
==== Liste als CSV exportieren
Wenn der Nutzer seine Filterergebnisse als CSV exportieren will
. nach der Filterung gibt es die Möglichkeit, die angezeigte Liste mit ihren Informationen als CSV zu exportieren
. Kann einen Pfad zum Speichern auswählen, automatisch wird immer der Downloads-Ordner angesteuert
. Mit "Liste exportieren" wird diese als CSV gespeichert
////

=== Wesentliche Szenarios

*Veröffentlichung nach Schlagwort filtern*

* Sc1: Der Autor B möchte eine Liste mit allen Veröffentlichungen, welche als Art der Veröffentlichung "Workshop" aufweisen. Autor B gibt in das Suchfeld "Workshop" ein. Das System gibt alle Veröffentlichungen aus, die "Workshop" als Art der Veröffentlichung besitzen.


*Veröffentlichung nach Sortierung filtern*

* Sc2: Der Autor C will eine Übersicht der zuletzt veröffentlichten Fachbeiträge. Autor C wählt in der Übersichtsspalte des Datums der Veröffentlichung das Symbol zur Sortierung aus und stellt die Sortierung nach <absteigend sortieren> ein. Das System gibt Veröffentlichungen in absteigender Reihenfolge nach dem Datum aus.

===	Nachbedingungen
Der Autor oder das Sales Department hat eine Veröffentlichung gefunden.
