== Beiträge verwalten
===	Beiträge filtern, durchsuchen und exportieren

===	Kurzbeschreibung der Akteure
==== Reporter
Ein Reporter kann Reports erstellen, Statistiken einsehen (Top Autoren, Veröffentlichungen je Bereich, ...), alle Beiträge im System einsehen und bearbeiten.

==== Gruppenleiter
Ein Gruppenleiter kann aus Informationszwecken die Veröffentlichungen seiner unterstellten Mitarbeiter filtern, durchsuchen und einsehen.

=== Vorbedingungen
* Reporter/Gruppenleiter muss als solcher angemeldet sein
** Reporter kann *alle Beiträge* verwalten und bearbeiten
** Gruppenleiter erhält Suchergebnisse nur zu den Beiträgen, welche von Autoren stammen, *die ihm unterstehen*
* Es muss mindestens ein Beitrag im System existieren


=== Standardablauf (Basic Flow)

. Akteur möchte Beiträge filtern
. Kann unter "Beiträge suchen" in Suchleiste jegliche Informationen zu Attributen, Eigenschaften von Beiträgen etc. suchen
. Bekommt Ergebnis von der Suchmaschine


=== Unterabläufe (subflows)

==== Zeitraum der Veröffentlichung
. Zeitraum in einen sich öffnendem Kalender eingeben

=== Wesentliche Szenarios

==== Beiträge durchsuchen/filtern

. Es existiert eine Suchleiste, in welcher nach Namen (des Beitrags, des Autors), Art des Mediums Attributen, Geschäftsbereich des Autors, Datum der Veröffentlichung und Tags gesucht werden kann
. Zusätzlich dazu gibt es unter "Weitere Filter" die Möglichkeit, die folgenden Eigenschaften durchsuchen zu können:
* Art der Veröffentlichung (Drop-Down-Menü)
* Aktueller Status (Drop-Down-Menü)
* Zeitraum der Veröffentlichung
** es öffnet sich Kalender, wo "von ... bis" eingegeben werden kann
. Nach jeder Filterauswahl erscheint das neue Suchergebnis

==== Als CSV exportieren
* Bei gesamten Suchvorgang gibt es zu jeder Suchanfrage einen Button "Als CSV exportieren"
* Hier kann *immer* als CSV exportiert werden
* Es werden dann alle Elemente, die im Suchvorgang unter den gewählten Filtern gefunden wurden mit ihren gesamten Eigenschaften in einer Liste exportiert:

[%header]
|===
|Beitrag|Autor|Geschäftsbereich|Datum|Art|Medium|Aktueller Status|Tags
|===

==== Informationen zu einzelnen Beiträgen
* Der Akteur kann jeden Beitrag, den er findet, auswählen und sich damit zu diesem alle vorhandenen Informationen anzeigen lassen
* Auch hier gibt es die Möglichkeit, als CSV zu exportieren

===	Nachbedingungen

==== Suchergebnis
* Akteur erhält gewünschtes Suchergebnis
** z.B. Gruppenleiter kann sich über neue Beiträge seiner Mitarbeiter informieren
** Reporter kann z.B. korrekte Veröffentlichungstypen, Beschriftung, etc. kontrollieren und so das System pflegen

=== Besondere Anforderungen

==== Rechte des Reporters
Der Reporter kann im System alle Beiträge einsehen, bearbeiten, exportieren und verwalten. Das System zeigt ihm alle Beiträge an. Mit der Autorisierung erhält er alle Rechte.

==== Rechte des Gruppenleiters
Der Gruppenleiter kann lediglich die Beiträge der ihm Unterstehenden Mitarbeiter einsehen und exportieren, jedoch nicht bearbeiten. Das System zeigt daher auch nur die darauf zutreffenden Beiträge an. Mit der Autorisierung erhält er genannte Rechte. 
