= Projektplan: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute
:imagesdir: images

== Einführung
//Briefly describe the content of the project plan.
In diesem Projektplan wir das Vorgehen zur Erstellung eines Verwaltungssystems für die Firma Zeiss festgehalten. Grobe Meilensteine werden determiniert, Vorgehensmodelle festgelegt und ein High-Level Überblick über das Projekt erstellt.

== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.
=== Team
[%header]
|===
| Mitarbeiter | department | Role | Programmiersprachen
| Paul Stefan Joksch | Administration | Projekt Manager | -
| Nina Püschmann | Administration | Analyst | - (Python)
| Stephan Joneleit | Implementation | Environment | "C#/.NET"
| Vanessa Bayer | Implementation | Architecture |
| Jonas Hölzel | Logic | Deployment | C#, Dart (Flutter), C, Python
| Jean-Pierre  Kaiser | Logic | Tester | "C, (grundlagen Java, Python), Visual Basic, Pascal"
| Oliver Wünsche | UI | Developer | "C, Java, R, HTML, CSS, (Python)" 
| Peter Holland-Moritz | UI | Tester |"C,C++,Java,Bash,(Html,C#,CSS)"
|===

=== Beziehungen Der Themen

=== Kommunikations Kanäle
Als Kommunikationsplattform mit dem Auftragssteller hat sich Jitsy als am besten herausgestellt. Untereinander werden schnelle gespräche meist auf discord abgehalten. Die wöchentlichen Meetings auf Teams.

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

Wie vorgeschrieben wird in iterativen abläufen gearbeitet werden. Grundlage dafür wird der OpenUP sein. die Iterationen werden jeweils zwei Wochen andauern.
Jeden Sonntag wird es ein Meeting geben. Zur Mitte der 2. Iteration wird die letzte Iteration von jedem Bewertet, und die Ergebnisse zum letzten Sonntagsmeeting in der Iteration besprochen. +  
Als Projekt-Planungstool haben wir uns Für Github-Issues entschieden, die als Kanban angeordnet werden. +
Der scope des MVP wurde Mithilfe von Userstories, Wireframes und einem Domainmodell Festgelegt und am 04.12.21 vom Auftraggeber Genehmigt. das Vorgehen wurde von Auftraggeber verlangt, da er zur Überzeugung der Stakeholder seinerseits ein Minimal Viable Product bis zum 27.01.21 benötigt. 
Beim erstellen des MVP haben sich einige Probleme ergeben. Wir haben die Ersten 2 Iterationen darauf verwendet das Gesamtprogramm zu planen, zum Ende der 2 Iteration wurde uns Klar, dass wir statt einem Prototypen ein MVP bereitzustellen haben. In dem Verlauf haben wir den Fehler gemacht nicht rechtzeitig auszuloten, welche Abteilung schon mit Programmieren anfangen kann, und welche noch auf Analysen warten/selber bereitstellen muss. Hier hätte das UI-Team schon wesentlich früher anfangen können. Zudem haben wir die Wichtigkeit der Erfahrung in einer Programmiersprache bei der Auswahl dieser unterschätzt.

== Meilesteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase


[%header, cols="1,3a,2"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone

| I1
|
* LCO Meilenstein
| 
06.12.2020
| I3
| 
* LCA Meilenstein MVP
|
20.12.2020
| I4
| 
* IOC Meilenstein MVP
|
25.01.2021
| I4
|
* Release Minimal Working Product
|  
27.01.2021
| I9
|
 * IOC Meilenstein
| 
30.05.2021

| I11 
|
* Fertigstellung des Projektes
|
27.06.2021
|===

== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.

== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.
* Anforderungen von Tasks besser herausfinden
* selbst bei einer guten Aufgabenstellung gibt es Missverständnisse
* Regelmäßigeren E-mailkontakt mit Updates zum Stand des Produktes an Auftragsteller
* früher herausfinden, welche bereiche schon mit Programmieren anfangen können (früherer UI start)
* zweierteams parallel programmieren um Probleme kurzfristig klären zu können

